Updated files
darinacat87/goit-node.js-hw-02-06 pull request #2
Opened 2023-01-31 21:11 UTC by darinacat87

2023-02-01 17:25 UTC, Eastvarga requested changes
Є зауваження

2023-02-01 17:25 UTC, Eastvarga commented on controllers/contacts/getAll.js
> +  res.json({
res.json(contacts ) достатньо, зайва інформація не потрібна у тілі відповіді

2023-02-01 17:25 UTC, Eastvarga commented on controllers/contacts/removeById.js
> +  const result = await Contact.findByIdAndDelete(contactId);
а чому не повертаєте результат видалення - що повертає цей метод (.findByIdAndDelete), чому так робить не замислювались?

2023-02-01 17:25 UTC, Eastvarga commented on controllers/contacts/updateStatusContact.js
> +  });
теж саме зайва інформація res.status(200).json(result ) достатньо

2023-02-01 17:25 UTC, Eastvarga commented on models/contacts.js
> +const contactSchema = Joi.object({
Не плутайте схеми для БД тпа схеми для валідацій, вони не повинні бути у одному модулі. В них різне призначення

2023-02-01 17:25 UTC, Eastvarga commented on controllers/contacts/updateById.js
>  const removeById = async (req, res, next) => {
Дивна назва, та бивно що оновлення повертає код 201

2023-02-02 20:01 UTC, darinacat87 commented on controllers/contacts/removeById.js
> +  const result = await Contact.findByIdAndDelete(contactId);
Змінила код, щоб повертати видалений контакт

2023-02-02 20:02 UTC, darinacat87 commented on models/contacts.js
> +const contactSchema = Joi.object({
Перемістила схеми для валідацій в папку schema

2023-02-02 20:04 UTC, darinacat87 commented on controllers/contacts/updateById.js
>  const removeById = async (req, res, next) => {
забула змінити при копіюванні коду з операції видалення. Пофіксила

2023-02-02 20:41 UTC, Eastvarga approved these changes

2023-02-02 20:41 UTC, merged